name: Dart CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
#      image:  google/dart:latest
      image: cirrusci/flutter:latest

    steps:
    - uses: actions/checkout@v1
    - name: Running flutter doctor
      run: flutter doctor
    - name: Install dependencies
      run: sudo /home/cirrus/sdks/flutter/bin/flutter pub get
    - name: Run tests
      run: sudo /home/cirrus/sdks/flutter/bin/flutter test
